version: "3.3"
services:
  db:
    image: mariadb:10.5.1
    container_name: db
    restart: always
    env_file: .env
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      TZ: America/Sao_Paulo
    volumes:
      - ./docker/storage/mysql-data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - app-network

  php:
    image: bitnami/php-fpm:7.3
    container_name: php
    restart: always
    volumes:
      - .:/app
    depends_on:
      - db
    links:
      - db
    ports:
      - "8000:8000"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
